import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import SetUser from '../helpers/SetUser';
import ButtonDefault from '../components/button/Button.style';

export default function Home() {

  SetUser()

  return (
    <main className={styles.index}>
      <Head>
        <title>Rock Paper Scissors</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-lizard.svg" />
      </Head>
     
      <nav className={styles.index__nav}>

        <Link href={'/lizard'}>
            <div className={styles.index__button}>
                 <ButtonDefault value="lizard Mode" border="transparent"/>
                  <span className={styles.button__icon}>
                    <Image src="/icon-lizard.svg" alt='icon-lizard.svg' width={30} height={30} className={styles.button__iconSvg}/>
                  </span>
            </div>
        </Link>

        <Link href={'/normal'}>
            <div className={styles.index__button}>
            <ButtonDefault value="Normal Mode" border="transparent"/>
                  <span className={styles.button__icon}>
                     <Image src="/icon-rock.svg" alt='icon-rock.svg' width={30} height={30}  className={styles.button__iconSvg}/>
                  </span>
            </div>
        </Link>

          <Link href={'/records'}>
              <div className={styles.index__button}>
              <ButtonDefault value="Records" border="transparent"/>
                  <span className={styles.button__icon}>
                      <Image src="/icon-trophy.svg" alt='icon-trophy.svg' width={30} height={30}  className={styles.button__iconSvg}/>
                  </span>
              </div>
          </Link>

      </nav>
        
    </main>
  )
}
